package com.sctrcd.busspassws.rules

import com.sctrcd.buspassws.model.*;

declare Broj
    broj: int
end


rule "racunVeciOd200.000" salience 100
lock-on-active
    no-loop
    when
       $i: ItemCountUser( $popust: getPopust(), getCena() > 2000)
    then
       modify ($i) { setPopust($popust + 5), setOsnovnipopustCele("Osnovni popust 5%")}
    end

rule "starijiOd2god" salience 80
lock-on-active
    no-loop
    when
       $i: ItemCountUser( $popust: getPopust(), $danasnjiDatum: getDatum(), $datumRegistracije: getU().getDateOfRegistration(), $datumRegistracije <= $danasnjiDatum)
    then
       modify ($i) { setPopust($popust + 1), setDodatnipopustCele1("Dodatni popust 1% na ceo racun")}
    end

rule "srebrniZlatniKupac" salience 60
lock-on-active
    no-loop
    when
       $i: ItemCountUser( $popust: getPopust(), $tipKupca: getU().getBuyerProfile().getCategory.getName, $tipKupca == "SREBRNI" || $tipKupca == "ZLATNI")
    then
       modify ($i) { setPopust($popust + 1), setDodatnipopustCele2("1% GOLD/SILVER")}
    end



rule "dodatni3postoPopust" salience 40
lock-on-active
    no-loop
    when
    $v : Broj( $pom: getBroj())
    $i: ItemCountUser($listaItema: getItems(), $celaCena: getCena())
    ItemCount($cena: getPrice(), $cena > $celaCena / 2) from $listaItema
    then
       modify ($v) {setBroj($pom + 1)}
    end

rule "proveriDodatni3PostoPopust" salience 20
no-loop
    when
    $v: Broj( $broj: getBroj());
    $i: ItemCountUser( $popust: getPopust(), $cena: getCena(), $cena > 50000 && $broj >9)

    then
       modify ($i) { setPopust($popust + 3), setDodatnipopustCele3("Dodatni popust od 3%")}
    end

