package com.sctrcd.busspassws.rules

import com.sctrcd.buspassws.model.*;

declare Broj
    broj: int
end


rule "racunVeciOd200.000"
    no-loop
    when
       $i: ItemCountUser( $popust: getPopust(), getCena() > 200000)
    then
       modify ($i) { setPopust($popust + 5)}
    end

rule "starijiOd2god"
    no-loop
    when
       $i: ItemCountUser( $popust: getPopust(), $danasnjiDatum: getDatum(), $datumRegistracije: getU().getDateOfRegistration(), $datumRegistracije <= $danasnjiDatum)
    then
       modify ($i) { setPopust($popust + 1)}
    end

rule "srebrniZlatniKupac"
    no-loop
    when
       $i: ItemCountUser( $popust: getPopust(), $tipKupca: getU().getBuyerProfile().getCategory.getName, $tipKupca == "SREBRNI" || $tipKupca == "ZLATNI")
    then
       modify ($i) { setPopust($popust + 1)}
    end



rule "dodatni3postoPopust"
    no-loop
    when
    $v : Broj( $pom: getBroj())
    $i: ItemCountUser($listaItema: getItems(), $celaCena: getCena())
    ItemCount($cena: getPrice(), $cena > $celaCena / 2) from $listaItema
    then
       modify ($v) {setBroj($pom + 1)}
    end

rule "proveriDodatni3PostoPopust"
no-loop
    when
    $v: Broj( $broj: getBroj());
    $i: ItemCountUser( $popust: getPopust(), $cena: getCena(), $cena > 50000 && $broj >9)

    then
       modify ($i) { setPopust($popust + 3)}
    end